### ISSUE TITLE
To-Do List of Things To Do

### ISSUE THREAD

**Issue by noisiver** [noisiver/mod-progression#8]
### DO NOT POST ANY COMMENTS HERE

This acts as a reminder to myself and some of it should be interpreted as a **long-term** goal. I won't give an estimate on when I'll start working on any of these or when I will be done with them. I'm working on it when I have the time to, and the only exception is if something breaks the balance of a patch. An example of this is higher tier of equipment available from vendors when they shouldn't be.

I can't think of absolutely everything so I will be adding things to this list as I discover them. It's extremely limited right now, but I wanted to start keeping track of things I need to do.

I shouldn't have to mention that things listed means I need to change it so they only appear when the patch they were added in is enabled.

### Professions
- [ ] Remove recipes for weapons and armor pieces from all trainers
- [ ] Remove recipes other than weapons and armor pieces from all trainers
- [ ] Remove recipes for weapons and armor pieces from all vendor and loot tables
- [ ] Remove recipes other than weapons and armor pieces from all vendor and loot tables

### Raids
- [ ] Level 60 version of Onyxia's Lair
- [ ] Level 60 version of Naxxramas

### Events
- [ ] Gates of Ahn'Qiraj
- [ ] Battle for the Dark Portal
